# Generated by Django 5.2 on 2025-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_public_id_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
